# Generated by Django 6.0.5 on 2026-05-26 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='account_type',
            field=models.CharField(choices=[('individual', 'Individual Volunteer'), ('ngo', 'NGO / Organization')], default='individual', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_size',
            field=models.PositiveIntegerField(blank=True, help_text='Approximate number of members', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_type',
            field=models.CharField(blank=True, choices=[('environmental', 'Environmental NGO'), ('corporate', 'Corporate CSR Group'), ('educational', 'Educational Institution'), ('community', 'Community / Resident Group'), ('religious', 'Religious / Cultural Group'), ('government', 'Government Body'), ('other', 'Other')], max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization_website',
            field=models.URLField(blank=True),
        ),
    ]
