# Generated by Django 6.0.5 on 2026-05-26 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_app', '0002_badge_min_points'),
        ('volunteers_app', '0002_userprofile_account_type_and_more'),
    ]

    operations = [
    ]
