# Generated by Django 6.0.5 on 2026-05-26 08:36

import secrets
from django.db import migrations, models


def generate_event_codes(apps, schema_editor):
    Event = apps.get_model('events_app', 'Event')
    for event in Event.objects.all():
        event.event_code = 'CLT-' + secrets.token_hex(4).upper()
        event.save(update_fields=['event_code'])


class Migration(migrations.Migration):

    dependencies = [
        ('events_app', '0002_worklog'),
    ]

    operations = [
        # Step 1: add without unique so existing rows can be populated
        migrations.AddField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=16, default=''),
            preserve_default=False,
        ),
        # Step 2: populate unique codes for all existing rows
        migrations.RunPython(generate_event_codes, migrations.RunPython.noop),
        # Step 3: now apply the unique constraint
        migrations.AlterField(
            model_name='event',
            name='event_code',
            field=models.CharField(blank=True, max_length=16, unique=True),
        ),
    ]
