# Generated by Django 6.0.5 on 2026-05-25 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('ecology_info', models.TextField(blank=True, help_text='Describe the ecological importance of this lake.', verbose_name='Ecological Importance')),
                ('current_status', models.TextField(blank=True, help_text='Describe the current condition of the lake.')),
                ('cleanup_needs', models.TextField(blank=True, help_text='Describe what clean-up activities are needed.', verbose_name='Clean-up Needs')),
                ('area_sq_km', models.FloatField(blank=True, null=True, verbose_name='Area (sq km)')),
                ('pollution_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LakePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='lake_photos/')),
                ('image_url', models.URLField(blank=True, help_text='Or provide an external image URL')),
                ('caption', models.CharField(blank=True, max_length=300)),
                ('photo_type', models.CharField(choices=[('before', 'Before Clean-up'), ('after', 'After Clean-up'), ('general', 'General')], default='general', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='lakes_app.lake')),
            ],
        ),
    ]
